apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-services
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: vault
        namespace: vault
        chart: vault
        repo: https://helm.releases.hashicorp.com
        version: 0.29.1
        values:
          global:
            enabled: true
          csi:
            enabled: true
          injector:
            enabled: true
          server:
            enabled: true
            dataStorage:
              storageClass: '{{ .storageClass | default "standard" }}'
            serviceAccount:
              name: vault
            standalone:
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                storage "file" {
                  path = "/vault/data"
                }
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: local-ca-issuer
              tls:
                - secretName: vault-tls
                  hosts:
                    - vault.{{ .dnsSuffix | default "local" }}
              hosts:
                - host: vault.{{ .dnsSuffix | default "local" }}
            extraVolumes:
            - type: configMap
              name: local-ca
            extraVolumeMounts:
            - name: local-ca
              mountPath: /etc/ssl/certs/local-ca.pem
              subPath: CA.cer
              readOnly: false
            hostAliases:
            - ip: '{{ .clusterIP | default "127.0.0.1" }}'
              hostnames:
              - vault.{{ .dnsSuffix | default "local" }}
  - git:
      repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
      revision: main
      files:
      - path: "local-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            {{- toYaml .values | nindent 12 }}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
