apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
          - list:
              elements:
                - name: grafana
                  namespace: grafana
                  chart: grafana
                  repo: https://grafana.github.io/helm-charts
                  version: 6.58.5
          - git:
              repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
              revision: main
              files:
                - path: "local-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            adminPassword: "admin"
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: local-ca-issuer
              hosts:
                - grafana.{{.dnsSuffix}}
              tls:
                - secretName: grafana-tls
                  hosts:
                    - grafana.{{.dnsSuffix}}
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                  - name: Mimir
                    type: prometheus
                    url: https://mimir.{{.dnsSuffix}}/prometheus
                    access: proxy
                    isDefault: true
                  - name: Loki
                    type: loki
                    url: https://loki.{{.dnsSuffix}}
                    access: proxy
                  - name: Tempo
                    type: tempo
                    url: https://tempo.{{.dnsSuffix}}
                    access: proxy
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
