apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
          - list:
              elements:
                - name: grafana
                  namespace: grafana
                  chart: grafana
                  repo: https://grafana.github.io/helm-charts
                  version: 6.58.5
          - git:
              repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
              revision: main
              files:
                - path: "local-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          valuesObject:
            ingress:
              enabled: true
              ingressClassName: "nginx"
              annotations:
                cert-manager.io/cluster-issuer: "local-ca-issuer"
              hosts:
                - "grafana.{{.dnsSuffix}}"
              tls:
                - secretName: "grafana-tls"
                  hosts:
                    - "grafana.{{.dnsSuffix}}"
            extraVolumes:
              - name: local-ca
                configMap:
                  name: local-ca
            extraVolumeMounts:
              - name: local-ca
                mountPath: /etc/ssl/certs/ca.crt
                subPath: CA.cer
            hostAliases:
            - ip: '{{.clusterIP}}'
              hostnames:
              - mimir.{{.dnsSuffix}}
              - loki.{{.dnsSuffix}}
              - tempo.{{.dnsSuffix}}
              - grafana.{{.dnsSuffix}}
            grafana.ini:
              server:
                root_url: "https://grafana.{{.dnsSuffix}}"
                enable_gzip: true
              auth:
                oauth_allow_insecure_email_lookup: true
            datasources:
              datasources.yaml:
                apiVersion: 1
                datasources:
                - name: Mimir
                  type: prometheus
                  uid: PAE45454D0EDB9216
                  url: "https://mimir.{{.dnsSuffix}}/prometheus"
                  access: proxy
                  isDefault: true
                  jsonData:
                    tlsSkipVerify: false
                    tlsAuthWithCACert: true
                  secureJsonData:
                    tlsCaCert: "@file:/etc/ssl/certs/ca.crt"
                - name: Loki
                  type: loki
                  uid: loki
                  url: "https://loki.{{.dnsSuffix}}"
                  access: proxy
                  jsonData:
                    tlsSkipVerify: false
                    tlsAuthWithCACert: true
                  secureJsonData:
                    tlsCaCert: "@file:/etc/ssl/certs/ca.crt"
                - name: Tempo
                  type: tempo
                  uid: tempo
                  url: "https://tempo.{{.dnsSuffix}}"
                  access: proxy
                  jsonData:
                    tlsSkipVerify: false
                    tlsAuthWithCACert: true
                  secureJsonData:
                    tlsCaCert: "@file:/etc/ssl/certs/ca.crt"
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
            dashboards: {}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
