apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - name: otel-collector
                namespace: otel-collector
                chart: opentelemetry-collector
                repo: https://open-telemetry.github.io/opentelemetry-helm-charts
                version: 0.139.1
        - git:
            repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
            revision: main
            files:
              - path: "local-cluster/config/cluster-params.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
