apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    global:
      enabled: true
    csi:
      enabled: true
    injector:
      enabled: true
    server:
      enabled: true
      dataStorage:
        storageClass: ${storgeClass}
      serviceAccount:
        name: vault
      standalone:
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "file" {
            path = "/vault/data"
          }
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: local-ca-issuer
        tls:
          - secretName: vault-tls
            hosts:
              - vault.${dnsSuffix}
        hosts:
          - host: vault.${dnsSuffix}
  postRenderers:
    - kustomize:
        patches:
        - target:
            kind: StatefulSet
            name: vault
          patch: |-
            - op: add
              path: /spec/template/spec/hostAliases
              value:
                - ip: ${clusterIP}
                  hostnames:
                  - "vault.${dnsSuffix}"

            - op: add
              path: /spec/template/spec/volumes/-
              value:
                name: local-ca
                configMap:
                  name: local-ca

            - op: add
              path: /spec/template/spec/containers/0/volumeMounts/-
              value:
                name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false

        - target:
            kind: Ingress
            name: vault
          patch: |-
            - op: add
              path: /spec/ingressClassName
              value: nginx