apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - name: otel-collector
                namespace: otel-collector
                chart: opentelemetry-collector
                repo: https://open-telemetry.github.io/opentelemetry-helm-charts
                version: 0.139.1
        - git:
            repoURL: 'https://github.com/pc-dae/observability-hub-poc.git'
            revision: main
            files:
              - path: "local-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            fullnameOverride: otel-collector
            image:
              repository: "otel/opentelemetry-collector-contrib"
              tag: "0.139.0"
            mode: daemonset
            service:
              enabled: true
            extraEnvs:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            extraVolumes:
            - name: local-ca
              configMap:
                name: local-ca
            extraVolumeMounts:
            - name: local-ca
              mountPath: /etc/ssl/certs/ca.crt
              subPath: CA.cer
            hostAliases:
            - ip: '{{.clusterIP}}'
              hostnames:
              - mimir.{{.dnsSuffix}}
              - loki.{{.dnsSuffix}}
              - tempo.{{.dnsSuffix}}
            presets:
              logsCollection:
                enabled: true
              hostMetrics:
                enabled: true
              kubeletMetrics:
                enabled: true
              kubernetesAttributes:
                enabled: true
            config:
              receivers:
                hostmetrics:
                  collection_interval: 10s
                  scrapers:
                    cpu: {}
                    memory: {}
                kubeletstats:
                  insecure_skip_verify: true
              processors:
                k8sattributes:
                  auth_type: "serviceAccount"
                  passthrough: false
                  filter:
                    node_from_env_var: K8S_NODE_NAME 
                  extract:
                    metadata:
                      - k8s.node.name
                      - k8s.pod.name
                  pod_association:
                    - sources:
                        - from: resource_attribute
                          name: k8s.pod.name
                    - sources:
                        - from: resource_attribute
                          name: k8s.pod.uid
                    - sources:
                        - from: connection
                resource/set_unique_host:
                  attributes:
                    - key: host.name
                      from_attribute: k8s.node.name
                      action: upsert
                batch: {}
                memory_limiter:
                  check_interval: 1s
                  limit_percentage: 75
                  spike_limit_percentage: 15
              exporters:
                otlphttp/mimir:
                  endpoint: "https://mimir.{{.dnsSuffix}}/otlp"
                  headers:
                    X-Scope-OrgID: "fake"
                  tls:
                    ca_file: /etc/ssl/certs/ca.crt
                otlphttp/loki:
                  endpoint: "https://loki.{{.dnsSuffix}}/otlp"
                  headers:
                    X-Scope-OrgID: "fake"
                  tls:
                    ca_file: /etc/ssl/certs/ca.crt
                otlphttp/tempo:
                  endpoint: "https://tempo.{{.dnsSuffix}}"
                  headers:
                    X-Scope-OrgID: "fake"
                  tls:
                    ca_file: /etc/ssl/certs/ca.crt
              service:
                pipelines:
                  traces:
                    receivers: [otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlphttp/tempo]
                  metrics:
                    receivers: [otlp, kubeletstats, hostmetrics]
                    processors: [memory_limiter, k8sattributes, resource/set_unique_host, batch]
                    exporters: [otlphttp/mimir]
                  logs:
                    receivers: [otlp, filelog]
                    processors: [memory_limiter, k8sattributes, batch]
                    exporters: [otlphttp/loki]
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
