apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  chart:
    spec:
      chart: kafka
      version: 31.2.0
      sourceRef:
        kind: HelmRepository
        name: kafka
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
  values:
    provisioning:
      enabled: true
      automountServiceAccountToken: true
      numPartitions: 1
      replicationFactor: 1
      topics:
        - name: infra
          partitions: 1
          replicationFactor: 1
          config:
            max.message.bytes: 64000
            flush.messages: 1
      