apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: grafana
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://mimir-nginx.monitoring.svc/prometheus
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "fake"
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "fake"
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc:3100
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "fake"

