apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: otel-collector
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.50.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: "deployment"
    config:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
      processors:
        batch:
        memory_limiter:
          check_interval: 1s
          limit_percentage: 75
          spike_limit_percentage: 15
      exporters:
        otlphttp/mimir:
          endpoint: "http://mimir.monitoring.svc.cluster.local/otlp"
        otlphttp/loki:
          endpoint: "http://loki.monitoring.svc.cluster.local/otlp"
        otlphttp/tempo:
          endpoint: "http://tempo.monitoring.svc.cluster.local/otlp"
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [otlphttp/tempo]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [otlphttp/mimir]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [otlphttp/loki]
