apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: mimir-distributed
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    mimir:
      structuredConfig:
        alertmanager:
          data_dir: /data/alertmanager
        ruler:
          alertmanager_url: http://localhost:8080/alertmanager
    alertmanager:
      enabled: true
    rollout_operator:
      enabled: false
    nginx:
      enabled: true
