apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kyverno.github.io/kyverno'
    chart: kyverno
    targetRevision: 3.3.4
    helm:
      values: |
        installCRDs: true
        cleanupController:
          enabled: false
        admissionController:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
      postRenderer:
        kustomize:
          patches:
          - target:
              group: apiextensions.k8s.io
              version: v1
              kind: CustomResourceDefinition
              annotationSelector: helm.sh/hook=crd-install
            patch: |
              - op: remove
                path: /metadata/annotations/meta.helm.sh~1release-name
              - op: remove
                path: /metadata/annotations/meta.helm.sh~1release-namespace
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
