apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.5.3"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: kube-system
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
    crds: CreateReplace
  interval: 10m0s
  timeout: 5m
