apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
